# Generated by Django 3.2 on 2021-04-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='out_stages',
        ),
        migrations.AddField(
            model_name='stage',
            name='in_stages',
            field=models.ManyToManyField(related_name='_journalAPI_stage_in_stages_+', to='journalAPI.Stage'),
        ),
    ]
