# Generated by Django 3.2 on 2021-04-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalAPI', '0002_auto_20210429_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='in_stages',
            field=models.ManyToManyField(null=True, related_name='_journalAPI_stage_in_stages_+', to='journalAPI.Stage'),
        ),
    ]
