# Generated by Django 3.2 on 2021-04-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalAPI', '0004_alter_stage_in_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='in_stages',
            field=models.ManyToManyField(blank=True, related_name='out_stages', to='journalAPI.Stage'),
        ),
    ]
