# Generated by Django 3.2 on 2021-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalAPI', '0005_alter_stage_in_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstagefiller',
            name='displayed_prev_stages',
            field=models.ManyToManyField(blank=True, related_name='displayed_following_stages', to='journalAPI.Stage'),
        ),
    ]
