# Generated by Django 3.2 on 2021-04-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalAPI', '0006_alter_taskstagefiller_displayed_prev_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='in_tasks',
            field=models.ManyToManyField(blank=True, related_name='out_tasks', to='journalAPI.Task'),
        ),
    ]
