# Generated by Django 3.2 on 2021-04-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journalAPI', '0007_alter_task_in_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='journalAPI.campaign'),
        ),
    ]
