# Generated by Django 3.2 on 2021-04-30 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='api.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.chain')),
                ('in_stages', models.ManyToManyField(blank=True, related_name='out_stages', to='api.Stage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebHookStageFiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_schema', models.JSONField(null=True)),
                ('ui_schema', models.JSONField(null=True)),
                ('library', models.CharField(blank=True, max_length=200)),
                ('web_hook_address', models.TextField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chain')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.stage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskStageFiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_schema', models.JSONField(null=True)),
                ('ui_schema', models.JSONField(null=True)),
                ('library', models.CharField(blank=True, max_length=200)),
                ('copy_input', models.BooleanField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chain')),
                ('displayed_prev_stages', models.ManyToManyField(blank=True, related_name='displayed_following_stages', to='api.Stage')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.stage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.case')),
                ('in_tasks', models.ManyToManyField(blank=True, related_name='out_tasks', to='api.Task')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.taskstagefiller')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionalStageFiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.JSONField(null=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chain')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.stage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='case',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.chain'),
        ),
    ]
