# Generated by Django 3.2.7 on 2021-10-05 08:02

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Instance name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Instance description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Instance name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Instance description')),
                ('campaign', models.ForeignKey(help_text='Campaign id', on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='api.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Instance name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Instance description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Instance name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Instance description')),
                ('x_pos', models.DecimalField(decimal_places=14, help_text="Starting position of 'x' coordinate to draw on Giga Turnip Chain frontend interface", max_digits=17)),
                ('y_pos', models.DecimalField(decimal_places=14, help_text="Starting position of 'y' coordinate to draw on Giga Turnip Chain frontend interface", max_digits=17)),
                ('chain', models.ForeignKey(help_text='Chain id', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.chain')),
                ('in_stages', models.ManyToManyField(blank=True, help_text='List of previous id stages', related_name='out_stages', to='api.Stage')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.stage_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ConditionalStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.stage')),
                ('conditions', models.JSONField(help_text='JSON logic conditions', null=True)),
                ('pingpong', models.BooleanField(default=False, help_text="If True, makes 'in stages' task incomplete")),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.stage',),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Instance name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Instance description')),
                ('campaign', models.ForeignKey(help_text='Campaign id', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.campaign')),
                ('default_rank', models.ForeignKey(blank=True, help_text='Rank id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rank')),
                ('ranks', models.ManyToManyField(help_text='Ranks id', related_name='ranks', to='api.Rank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RankRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.ForeignKey(help_text='Rank id', on_delete=django.db.models.deletion.CASCADE, to='api.rank')),
                ('user', models.ForeignKey(help_text='User id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='CampaignManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_managements', to='api.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_managements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'campaign')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='default_track',
            field=models.ForeignKey(blank=True, help_text='Default track id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_campaigns', to='api.track'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='managers',
            field=models.ManyToManyField(related_name='managed_campaigns', through='api.CampaignManagement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ranks',
            field=models.ManyToManyField(related_name='users', through='api.RankRecord', to='api.Rank'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.stage')),
                ('json_schema', models.TextField(blank=True, help_text='Defines the underlying data to be shown in the UI (objects, properties, and their types)', null=True)),
                ('ui_schema', models.TextField(blank=True, help_text='Defines how JSON data is rendered as a form, e.g. the order of controls, their visibility, and the layout', null=True)),
                ('library', models.CharField(blank=True, help_text='Type of JSON form library', max_length=200)),
                ('rich_text', models.TextField(blank=True, help_text='Text field with rich HTML formatting, can be used for manuals', null=True)),
                ('copy_input', models.BooleanField(default=False)),
                ('allow_multiple_files', models.BooleanField(default=False, help_text='Allow user to upload multiple files')),
                ('is_creatable', models.BooleanField(default=False, help_text='Allow user to create a task manually')),
                ('assign_user_by', models.CharField(choices=[('RA', 'Rank'), ('ST', 'Stage')], default='RA', help_text="User assignment method (by 'Stage' or by 'Rank')", max_length=2)),
                ('webhook_address', models.URLField(blank=True, help_text='Webhook URL address. If not empty, field indicates that task should be given not to a user in the system, but to a webhook. Only data from task directly preceding webhook is sent. All fields related to user assignment are ignored,if this field is not empty.', max_length=1000, null=True)),
                ('webhook_payload_field', models.TextField(blank=True, help_text='JSON field name to put outgoing data into. Ignored if webhook_address field is empty.', null=True)),
                ('webhook_params', models.JSONField(blank=True, help_text='Get parameters sent to webhook.', null=True)),
                ('webhook_response_field', models.TextField(blank=True, help_text='JSON response field name to extract data from. Ignored if webhook_address field is empty.', null=True)),
                ('assign_user_from_stage', models.ForeignKey(blank=True, help_text='Stage id. User from assign_user_from_stage will be assigned to a task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_user_to_stages', to='api.stage')),
                ('displayed_prev_stages', models.ManyToManyField(blank=True, help_text='List of previous stages (tasks data) to be shown in current stage', related_name='displayed_following_stages', to='api.Stage')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.stage', models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(blank=True, help_text='User generated responses (answers)', null=True)),
                ('complete', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(blank=True, help_text='User id who is responsible for the task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, help_text='Case id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.case')),
                ('in_tasks', models.ManyToManyField(blank=True, help_text='Preceded tasks', related_name='out_tasks', to='api.Task')),
                ('stage', models.ForeignKey(help_text='Stage id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.taskstage')),
            ],
        ),
        migrations.CreateModel(
            name='RankLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_limit', models.IntegerField(default=0, help_text='The maximum number of tasks that can be opened at the same time for a user')),
                ('total_limit', models.IntegerField(default=0, help_text='The maximum number of tasks that user can obtain')),
                ('is_listing_allowed', models.BooleanField(default=False, help_text='Allow user to see the list of created tasks')),
                ('is_submission_open', models.BooleanField(default=True, help_text='Allow user to submit a task')),
                ('is_selection_open', models.BooleanField(default=True, help_text='Allow user to select a task')),
                ('is_creation_open', models.BooleanField(default=True, help_text='Allow user to create a task')),
                ('rank', models.ForeignKey(help_text='Rank id', on_delete=django.db.models.deletion.CASCADE, to='api.rank')),
                ('stage', models.ForeignKey(help_text='Stage id', on_delete=django.db.models.deletion.CASCADE, related_name='ranklimits', to='api.taskstage')),
            ],
            options={
                'unique_together': {('rank', 'stage')},
            },
        ),
        migrations.AddField(
            model_name='rank',
            name='stages',
            field=models.ManyToManyField(help_text='Stages id', related_name='ranks', through='api.RankLimit', to='api.TaskStage'),
        ),
    ]
