# Generated by Django 3.2.5 on 2021-07-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionalstage',
            name='x_pos',
        ),
        migrations.RemoveField(
            model_name='conditionalstage',
            name='y_pos',
        ),
        migrations.RemoveField(
            model_name='taskstage',
            name='x_pos',
        ),
        migrations.RemoveField(
            model_name='taskstage',
            name='y_pos',
        ),
        migrations.AddField(
            model_name='stage',
            name='x_pos',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='y_pos',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=17),
            preserve_default=False,
        ),
    ]
