# Generated by Django 3.2.1 on 2021-05-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.stage')),
                ('conditions', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.stage',),
        ),
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.stage')),
                ('json_schema', models.JSONField(null=True)),
                ('ui_schema', models.JSONField(null=True)),
                ('library', models.CharField(blank=True, max_length=200)),
                ('copy_input', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.stage', models.Model),
        ),
        migrations.CreateModel(
            name='WebHookStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.stage')),
                ('json_schema', models.JSONField(null=True)),
                ('ui_schema', models.JSONField(null=True)),
                ('library', models.CharField(blank=True, max_length=200)),
                ('web_hook_address', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.stage', models.Model),
        ),
        migrations.RemoveField(
            model_name='taskstagefiller',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='taskstagefiller',
            name='displayed_prev_stages',
        ),
        migrations.RemoveField(
            model_name='taskstagefiller',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='webhookstagefiller',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='webhookstagefiller',
            name='stage',
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='stage',
            name='in_stages',
        ),
        migrations.AddField(
            model_name='stage',
            name='out_stages',
            field=models.ManyToManyField(blank=True, related_name='in_stages', to='api.Stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.stage_set+', to='contenttypes.contenttype'),
        ),
        migrations.DeleteModel(
            name='ConditionalStageFiller',
        ),
        migrations.DeleteModel(
            name='WebHookStageFiller',
        ),
        migrations.AddField(
            model_name='taskstage',
            name='displayed_prev_stages',
            field=models.ManyToManyField(blank=True, related_name='displayed_following_stages', to='api.Stage'),
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.taskstage'),
        ),
        migrations.DeleteModel(
            name='TaskStageFiller',
        ),
    ]
