# Generated by Django 3.2.5 on 2021-07-07 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210705_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='conditionalstage',
            name='pingpong',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='api.campaign')),
                ('default_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rank')),
                ('ranks', models.ManyToManyField(related_name='tracks', to='api.Rank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RankStageLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_limit', models.IntegerField(default=0)),
                ('total_limit', models.IntegerField(default=0)),
                ('list_permission', models.BooleanField(default=False)),
                ('close_submission', models.BooleanField(default=False)),
                ('close_selection', models.BooleanField(default=False)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rank')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taskstage')),
            ],
        ),
        migrations.CreateModel(
            name='RankRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rank',
            name='stages',
            field=models.ManyToManyField(related_name='ranks', through='api.RankStageLimits', to='api.TaskStage'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='default_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_campaign', to='api.track'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ranks',
            field=models.ManyToManyField(related_name='users', through='api.RankRecord', to='api.Rank'),
        ),
    ]
