# Generated by Django 3.2.1 on 2021-06-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210505_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='allow_multiple_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='count_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='is_creatable',
            field=models.BooleanField(default=False),
        ),
    ]
