# Generated by Django 3.2.5 on 2021-07-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210707_0754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RankStageLimits',
            new_name='RankLimit',
        ),
        migrations.RemoveField(
            model_name='taskstage',
            name='count_complete',
        ),
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
