# Generated by Django 3.2.1 on 2021-06-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210622_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='x_pos',
            field=models.DecimalField(decimal_places=14, default=160, max_digits=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskstage',
            name='y_pos',
            field=models.DecimalField(decimal_places=14, default=372, max_digits=17),
            preserve_default=False,
        ),
    ]
