# Generated by Django 3.2.1 on 2021-06-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210629_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='node_type',
            field=models.TextField(choices=[('STAGE', 'Stage'), ('LOGIC', 'Logic'), ('PONG', 'Ping-pong')], default='STAGE'),
        ),
    ]
