# Generated by Django 3.2.5 on 2021-07-08 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210707_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='default_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_campaigns', to='api.track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.campaign'),
        ),
        migrations.AlterField(
            model_name='track',
            name='ranks',
            field=models.ManyToManyField(related_name='ranks', to='api.Rank'),
        ),
    ]
