# Generated by Django 3.2.1 on 2021-06-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_taskstage_copy_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstage',
            name='node_type',
        ),
        migrations.AddField(
            model_name='conditionalstage',
            name='x_pos',
            field=models.DecimalField(decimal_places=14, default=333, max_digits=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conditionalstage',
            name='y_pos',
            field=models.DecimalField(decimal_places=14, default=333, max_digits=17),
            preserve_default=False,
        ),
    ]
