# Generated by Django 3.2.5 on 2021-07-09 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210708_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='assign_user_by',
            field=models.CharField(choices=[('RA', 'Rank'), ('ST', 'Stage')], default='RA', max_length=2),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='assign_user_from_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_user_to_stages', to='api.stage'),
        ),
    ]
