# Generated by Django 3.2.5 on 2021-07-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210709_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='responses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
