# Generated by Django 3.2.5 on 2021-07-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210709_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='chain',
        ),
    ]
