# Generated by Django 3.2.6 on 2021-09-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210927_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstage',
            name='rich_text',
        ),
        migrations.RemoveField(
            model_name='webhookstage',
            name='rich_text',
        ),
    ]
