# Generated by Django 3.2.6 on 2021-09-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210927_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='rich_text',
            field=models.TextField(blank=True, help_text='Text field with rich HTML formatting, can be used for manuals', null=True),
        ),
    ]
