# Generated by Django 3.2.6 on 2021-09-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_taskstage_rich_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='webhook_address',
            field=models.URLField(blank=True, help_text='Webhook URL address. If not empty, field indicates that task should be given not to a user in the system, but to a webhook. Only data from task directly preceding webhook is sent. All fields related to user assignment are ignored,if this field is not empty.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='webhook_params',
            field=models.JSONField(help_text='Get parameters sent to webhook.', null=True),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='webhook_payload_field',
            field=models.TextField(blank=True, help_text='JSON field name to put outgoing data into. Ignored if webhook_address field is empty.', null=True),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='webhook_response_field',
            field=models.TextField(blank=True, help_text='JSON response field name to extract data from. Ignored if webhook_address field is empty.', null=True),
        ),
        migrations.DeleteModel(
            name='WebHookStage',
        ),
    ]
