# Generated by Django 3.2.6 on 2021-10-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210929_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstage',
            name='webhook_params',
            field=models.JSONField(blank=True, help_text='Get parameters sent to webhook.', null=True),
        ),
    ]
