# Generated by Django 3.2.8 on 2021-10-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_taskstage_webhook_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='open',
            field=models.BooleanField(default=False, help_text='If True, users can join'),
        ),
    ]
