# Generated by Django 3.2.8 on 2021-10-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_campaign_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='ranks',
        ),
    ]
