# Generated by Django 3.2.8 on 2021-10-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20211014_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='x_pos',
            field=models.DecimalField(decimal_places=3, help_text="Starting position of 'x' coordinate to draw on Giga Turnip Chain frontend interface", max_digits=17),
        ),
        migrations.AlterField(
            model_name='stage',
            name='y_pos',
            field=models.DecimalField(decimal_places=3, help_text="Starting position of 'y' coordinate to draw on Giga Turnip Chain frontend interface", max_digits=17),
        ),
    ]
