# Generated by Django 3.2.8 on 2021-10-29 14:00

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20211018_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('json', models.JSONField(blank=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(help_text='Campaign related to the issue in the log', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.campaign')),
                ('case', models.ForeignKey(blank=True, help_text='Case related to the issue in the log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.case')),
                ('chain', models.ForeignKey(blank=True, help_text='Chain related to the issue in the log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.chain')),
                ('rank', models.ForeignKey(blank=True, help_text='Rank related to the issue in the log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.rank')),
                ('rank_limit', models.ForeignKey(blank=True, help_text='RankLimit related to the issue in the log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.ranklimit')),
                ('rank_record', models.ForeignKey(blank=True, help_text='RankRecord related to the issue in the log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rr_logs', to='api.ranklimit')),
                ('stage', models.ForeignKey(blank=True, help_text='Stage related to the issue in the log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.stage')),
                ('task', models.ForeignKey(blank=True, help_text='Task related to the issue in the log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.task')),
                ('track', models.ForeignKey(blank=True, help_text='Track related to the issue in the log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.track')),
                ('user', models.ForeignKey(blank=True, help_text='User related to the issue in the log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, api.models.CampaignInterface),
        ),
    ]
