# Generated by Django 3.2.8 on 2021-11-01 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Time of creation'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Last update time'),
        ),
        migrations.AddField(
            model_name='campaignmanagement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Time of creation'),
        ),
        migrations.AddField(
            model_name='campaignmanagement',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Last update time'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Time of creation'),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Last update time'),
        ),
        migrations.AddField(
            model_name='chain',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Time of creation'),
        ),
        migrations.AddField(
            model_name='chain',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Last update time'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Time of creation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Last update time'),
        ),
        migrations.AddField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Time of creation'),
        ),
        migrations.AddField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Last update time'),
        ),
        migrations.AddField(
            model_name='rank',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Time of creation'),
        ),
        migrations.AddField(
            model_name='rank',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Last update time'),
        ),
        migrations.AddField(
            model_name='ranklimit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Time of creation'),
        ),
        migrations.AddField(
            model_name='ranklimit',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Last update time'),
        ),
        migrations.AddField(
            model_name='rankrecord',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Time of creation'),
        ),
        migrations.AddField(
            model_name='rankrecord',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Last update time'),
        ),
        migrations.AddField(
            model_name='stage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Time of creation'),
        ),
        migrations.AddField(
            model_name='stage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Last update time'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Time of creation'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Last update time'),
        ),
        migrations.AddField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Time of creation'),
        ),
        migrations.AddField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), help_text='Last update time'),
        ),
    ]
