# Generated by Django 3.2.8 on 2021-11-01 06:19

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update date')),
                ('name', models.CharField(help_text='Instance name', max_length=150)),
                ('message', models.TextField(blank=True, help_text='Text message', null=True)),
                ('important', models.BooleanField(default=False, help_text='True if important')),
                ('campaign', models.ForeignKey(help_text='Campaign id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.campaign')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, api.models.CampaignInterface),
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update date')),
                ('viewed', models.BooleanField(default=False, help_text='True if user open the message')),
                ('viewed_at', models.DateTimeField(blank=True, help_text='Date viewed', null=True)),
                ('message', models.ForeignKey(help_text='Message id', on_delete=django.db.models.deletion.CASCADE, related_name='message_statuses', to='api.message')),
                ('user', models.ForeignKey(help_text='User id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, api.models.CampaignInterface),
        ),
    ]
