# Generated by Django 3.2.8 on 2021-11-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_message_messagestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='', help_text='Instance title', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='important',
            field=models.IntegerField(default=3, help_text='The lower the more important'),
        ),
    ]
