# Generated by Django 3.2.8 on 2021-11-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_notification_notificationstatus'),
        ('api', '0028_auto_20211101_0725'),
    ]

    operations = [
    ]
