# Generated by Django 3.2.8 on 2021-11-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_adminpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='force_complete',
            field=models.BooleanField(default=False),
        ),
    ]
