# Generated by Django 3.2.8 on 2021-11-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_notification_target_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('task_stage', models.OneToOneField(help_text='Parent TaskStage', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='integration', serialize=False, to='api.taskstage')),
                ('group_by', models.TextField(blank=True, help_text='Top level Task responses keys for task grouping separated by whitespaces.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='integrator_group',
            field=models.JSONField(blank=True, default=None, help_text='Response fields that must be shared by all tasks being integrated.', null=True),
        ),
    ]
