# Generated by Django 3.2.8 on 2021-11-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20211118_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstage',
            name='assign_user_by',
            field=models.CharField(choices=[('RA', 'Rank'), ('ST', 'Stage'), ('IN', 'Integrator')], default='RA', help_text="User assignment method (by 'Stage' or by 'Rank')", max_length=2),
        ),
    ]
