# Generated by Django 3.2.8 on 2021-11-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='headers',
            field=models.JSONField(default=dict, help_text='Headers sent to webhook.'),
        ),
    ]
