# Generated by Django 3.2.8 on 2021-11-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_webhook_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='Headers sent to webhook.'),
        ),
    ]
