# Generated by Django 3.2.8 on 2021-11-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_webhook_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reopened',
            field=models.BooleanField(default=False, help_text='Indicates that task was returned to user, usually because of pingpong stages.'),
        ),
    ]
