# Generated by Django 3.2.8 on 2021-11-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_task_reopened'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('copy_by', models.CharField(choices=[('US', 'User')], default='US', help_text='Where to copy fields from', max_length=2)),
                ('fields_to_copy', models.TextField(help_text='List of responses field pairs to copy. \nFormat: original_field1->copy_field1  \nPairs are joined by arrow and separatedby whitespaces. \nExample: phone->observer_phone uik->uik ')),
                ('copy_from_stage', models.ForeignKey(help_text='Stage of the task that provides data being copied', on_delete=django.db.models.deletion.CASCADE, related_name='copycat_fields', to='api.taskstage')),
                ('task_stage', models.ForeignKey(help_text='Stage of the task that accepts data being copied', on_delete=django.db.models.deletion.CASCADE, related_name='copy_fields', to='api.taskstage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
