# Generated by Django 3.2.8 on 2021-11-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_copyfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='allow_go_back',
            field=models.BooleanField(default=False, help_text='Indicates that previous task can be opened.'),
        ),
    ]
