# Generated by Django 3.2.8 on 2021-11-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_taskstage_allow_go_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='allow_release',
            field=models.BooleanField(default=False, help_text='Indicates task can be released.'),
        ),
    ]
