# Generated by Django 3.2.8 on 2021-11-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_taskstage_allow_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Indicates tasks of this stage may be accessed by unauthenticated users.'),
        ),
    ]
