# Generated by Django 3.2.8 on 2021-12-01 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20211127_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagePublisher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('json_schema', models.TextField(blank=True, help_text='Defines the underlying data to be shown in the UI (objects, properties, and their types)', null=True)),
                ('ui_schema', models.TextField(blank=True, help_text='Defines how JSON data is rendered as a form, e.g. the order of controls, their visibility, and the layout', null=True)),
                ('library', models.CharField(blank=True, help_text='Type of JSON form library', max_length=200)),
                ('task_stage', models.OneToOneField(help_text='Stage of the task that will be published', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='publisher', serialize=False, to='api.taskstage')),
                ('exclude_fields', models.TextField(blank=True, help_text='List of all first level fields to exclude from publication separated by whitespaces.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
