# Generated by Django 3.2.8 on 2022-01-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_stagepublisher_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('task_stage', models.OneToOneField(help_text='Stage of the task that will be published', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quiz', serialize=False, to='api.taskstage')),
                ('correct_responses_task', models.OneToOneField(blank=True, help_text='Task containing correct responses to the quiz', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='api.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
