# Generated by Django 3.2.8 on 2022-01-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='threshold',
            field=models.FloatField(blank=True, help_text='If set, task will not be closed with quiz scores lower than this threshold', null=True),
        ),
    ]
