# Generated by Django 3.2.8 on 2022-01-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_quiz_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstage',
            name='assign_user_from_stage',
            field=models.ForeignKey(blank=True, help_text='Stage id. User from assign_user_from_stage will be assigned to a task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_user_to_stages', to='api.stage'),
        ),
    ]
