# Generated by Django 3.2.8 on 2022-01-31 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_taskstage_assign_user_from_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseFlattener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('copy_first_level', models.BooleanField(default=True, help_text='Copy all first level fields in responses that are not dictionaries or arrays.')),
                ('copy_system_fields', models.BooleanField(default=False, help_text='Copy all system fields fields in tasks.')),
                ('exclude_list', models.TextField(blank=True, help_text='List of all first level fields to exclude separated by whitespaces. Dictionary and array fields are excluded automatically.')),
                ('columns', models.JSONField(blank=True, default=list, help_text='List of columns with with paths to values inside. Also you can use: i - if you you want to find keys that have same word in key; r - if you want use regular expressions. For example: ["title", "oik__(i)uik", "oik__(r)question[\\d]{1,2}"]')),
                ('task_stage', models.ForeignKey(help_text='Stage of the task will be flattened.', on_delete=django.db.models.deletion.CASCADE, related_name='response_flatteners', to='api.taskstage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
