# Generated by Django 3.2.8 on 2022-02-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_responseflattener'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseFlattener',
        ),
    ]
