# Generated by Django 3.2.8 on 2022-03-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_responseflattener_flatten_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseflattener',
            name='exclude_list',
            field=models.JSONField(blank=True, default=list, help_text='List of all first level fields to exclude separated by whitespaces. Dictionary and array fields are excluded automatically.'),
        ),
        migrations.AlterField(
            model_name='responseflattener',
            name='task_stage',
            field=models.OneToOneField(help_text='Stage of the task will be flattened.', on_delete=django.db.models.deletion.CASCADE, related_name='response_flatteners', to='api.taskstage'),
        ),
    ]
