# Generated by Django 3.2.8 on 2022-05-18 12:15

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20220330_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstage',
            name='assign_user_by',
            field=models.CharField(choices=[('RA', 'Rank'), ('ST', 'Stage'), ('AU', 'Auto-complete')], default='RA', help_text="User assignment method (by 'Stage' or by 'Rank')", max_length=2),
        ),
        migrations.CreateModel(
            name='TaskAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('count', models.PositiveIntegerField(help_text='The count of completed tasks to give an award.')),
                ('title', models.TextField(help_text='Title for a message for users who achieve the award.', null=True)),
                ('message', models.TextField(help_text='Message for users who achieve award.')),
                ('message_before_achieve', models.TextField(help_text='Message for users about coming award.')),
                ('rank', models.ForeignKey(help_text='Rank to create the record with a user. It is a rank that will be given user, as an award who have completed a defined count of tasks', on_delete=django.db.models.deletion.CASCADE, to='api.rank')),
                ('task_stage_completion', models.ForeignKey(help_text='Task Stage completion. Usually, it is the stage that the user completes.', on_delete=django.db.models.deletion.CASCADE, related_name='task_stage_completion', to='api.taskstage')),
                ('task_stage_verified', models.ForeignKey(help_text='Task Stage verified. It is the stage that is checked by the verifier.', on_delete=django.db.models.deletion.CASCADE, related_name='task_stage_verified', to='api.taskstage')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, api.models.CampaignInterface),
        ),
    ]
