# Generated by Django 3.2.8 on 2022-06-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_dynamicjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='external_metadata',
            field=models.JSONField(blank=True, help_text='To show slides.', null=True),
        ),
    ]
