# Generated by Django 3.2.8 on 2022-06-20 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_previousmanual_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousmanual',
            name='task_stage',
        ),
        migrations.AddField(
            model_name='previousmanual',
            name='task_stage_email',
            field=models.OneToOneField(default=1672, help_text='Point to find previous task stage', on_delete=django.db.models.deletion.CASCADE, to='api.taskstage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previousmanual',
            name='task_stage_to_assign',
            field=models.OneToOneField(default=1649, help_text='Point to find previous task stage', on_delete=django.db.models.deletion.CASCADE, related_name='previous_manual_to_assign', to='api.taskstage'),
            preserve_default=False,
        ),
    ]
