# Generated by Django 3.2.8 on 2022-06-20 08:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20220620_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousmanual',
            name='field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), help_text='User have to enter path to the field where places users email to assign new task', size=None),
        ),
        migrations.AlterField(
            model_name='previousmanual',
            name='is_id',
            field=models.BooleanField(default=False, help_text='If True, user have to enter id. Otherwise, user have to enter email'),
        ),
        migrations.AlterField(
            model_name='previousmanual',
            name='task_stage_email',
            field=models.OneToOneField(help_text='Task stage to get email from responses to assign task', on_delete=django.db.models.deletion.CASCADE, to='api.taskstage'),
        ),
        migrations.AlterField(
            model_name='previousmanual',
            name='task_stage_to_assign',
            field=models.OneToOneField(help_text='This task will assign to the user. Also, you have to set assign_user_by as PM in this TaskStage to use manual assignment.', on_delete=django.db.models.deletion.CASCADE, related_name='previous_manual_to_assign', to='api.taskstage'),
        ),
        migrations.AlterField(
            model_name='taskstage',
            name='assign_user_by',
            field=models.CharField(choices=[('RA', 'Rank'), ('ST', 'Stage'), ('AU', 'Auto-complete'), ('PA', 'Previous manual')], default='RA', help_text='User assignment method.\nRank means that all task assignments will be based on ranks. If the user has this rank.\nStage means that created task will be assign automatically based on assign_user_from_stage. So you must pass assign_user_from_stage if you choose assign_user_by.\nAuto-complete means that this task will complete automatically without any condition.\nPrevious manual means that task will assign manually by user. For this feature You must create new instance in Previous Manual model and pass this stage in field task_stage_to_assign.', max_length=2),
        ),
    ]
