# Generated by Django 3.2.8 on 2022-06-20 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20220620_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicjson',
            name='webhook_address',
        ),
        migrations.AddField(
            model_name='dynamicjson',
            name='webhook',
            field=models.ForeignKey(help_text='Webhook using for updating schema answers', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.webhook'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='is_triggered',
            field=models.BooleanField(default=True, help_text='Sometimes there are cases when a webhook is used by a non-taskstage and then we need to mark it accordingly'),
        ),
    ]
