# Generated by Django 3.2.8 on 2022-06-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20220620_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicjson',
            name='webhook',
            field=models.ForeignKey(blank=True, help_text='Webhook using for updating schema answers', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.webhook'),
        ),
    ]
