# Generated by Django 3.2.8 on 2022-06-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_dynamicjson_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sms_login_allow',
            field=models.BooleanField(default=False, help_text='User that logged in via sms can enter in the campaign'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_via_sms',
            field=models.BooleanField(default=False, help_text='User is login via sms'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Users phone number', max_length=250),
        ),
    ]
