# Generated by Django 3.2.8 on 2022-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20220629_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskaward',
            name='stop_chain',
            field=models.BooleanField(default=False, help_text='When rank will obtained by user chain will stop.'),
        ),
    ]
