# Generated by Django 3.2.8 on 2022-07-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_taskaward_stop_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update date')),
                ('go_forward', models.BooleanField(default=True, help_text='If process will go forward notification will be sent. Otherwise process goes back and previous task is returned.')),
                ('notification', models.ForeignKey(help_text='Notification that will be using for get user', on_delete=django.db.models.deletion.CASCADE, to='api.notification')),
                ('recipient_stage', models.ForeignKey(help_text='Stage to get recipient user.', on_delete=django.db.models.deletion.CASCADE, related_name='auto_notification_recipient_stages', to='api.taskstage')),
                ('trigger_stage', models.ForeignKey(help_text='Stage that will be trigger notification', on_delete=django.db.models.deletion.CASCADE, related_name='auto_notification_trigger_stages', to='api.taskstage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
