# Generated by Django 3.2.8 on 2022-07-20 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_autonotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskaward',
            name='message',
        ),
        migrations.RemoveField(
            model_name='taskaward',
            name='message_before_achieve',
        ),
        migrations.RemoveField(
            model_name='taskaward',
            name='title',
        ),
        migrations.AddField(
            model_name='taskaward',
            name='notification',
            field=models.ForeignKey(blank=True, help_text='Notification which will be sent on achieving new rank.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.notification'),
        ),
    ]
