# Generated by Django 3.2.8 on 2022-07-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20220720_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autonotification',
            name='go_forward',
        ),
        migrations.AddField(
            model_name='autonotification',
            name='go',
            field=models.CharField(choices=[('FW', 'Forward'), ('BW', 'Backward'), ('LO', 'Last-one')], default='FW', help_text='You have to choose on what action notification would be sent.', max_length=2),
        ),
    ]
