# Generated by Django 3.2.8 on 2022-07-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20220720_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='prerequisite_ranks',
            field=models.ManyToManyField(blank=True, help_text='Preceded tasks', related_name='postrequisite_ranks', to='api.Rank'),
        ),
    ]
