# Generated by Django 3.2.8 on 2022-08-09 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_rank_prerequisite_ranks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankrecord',
            name='user',
            field=models.ForeignKey(help_text='User id', on_delete=django.db.models.deletion.CASCADE, related_name='user_ranks', to=settings.AUTH_USER_MODEL),
        ),
    ]
