# Generated by Django 3.2.8 on 2022-08-17 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20220816_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='trigger_task',
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_notifications', to='api.task'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notifications', to='api.task'),
        ),
    ]
