# Generated by Django 3.2.8 on 2022-08-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20220817_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='card_json_schema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='card_ui_schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
