# Generated by Django 3.2.8 on 2022-09-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20220822_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='default_track',
            field=models.ForeignKey(blank=True, help_text='Default track id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_campaigns', to='api.track'),
        ),
    ]
