# Generated by Django 3.2.8 on 2022-09-29 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_campaign_default_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpreference',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
