# Generated by Django 3.2.8 on 2022-10-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_conditionallimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.URLField(default='https://www.thisrowwasempty.com', help_text='Webhook URL address. If not empty, field indicates that task should be given not to a user in the system, but to a webhook. Only data from task directly preceding webhook is sent. All fields related to user assignment are ignored,if this field is not empty.', max_length=1000),
            preserve_default=False,
        ),
    ]
