# Generated by Django 3.2.8 on 2022-10-24 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_alter_webhook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatetimeSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('start_time', models.DateTimeField(blank=True, help_text='the time when the task should open', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='the time when the task should close', null=True)),
                ('stage', models.OneToOneField(help_text='step sorted by datetime', on_delete=django.db.models.deletion.CASCADE, related_name='datetime_sort', to='api.stage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
