# Generated by Django 3.2.8 on 2022-11-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_dynamicjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimesort',
            name='after_how_much',
            field=models.FloatField(blank=True, help_text='how long does it take to open a task', null=True),
        ),
        migrations.AddField(
            model_name='datetimesort',
            name='how_much',
            field=models.FloatField(blank=True, help_text='how long to open the task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_period',
            field=models.DateTimeField(blank=True, help_text='the time until which this task is available', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_period',
            field=models.DateTimeField(blank=True, help_text='the time from which this task is available', null=True),
        ),
    ]
