# Generated by Django 3.2.8 on 2022-11-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20221109_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicjson',
            name='obtain_options_from_stage',
            field=models.BooleanField(default=False, help_text='Get options from another stages.'),
        ),
    ]
