# Generated by Django 3.2.8 on 2022-12-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_dynamicjson_obtain_options_from_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimesort',
            name='after_how_much',
            field=models.FloatField(blank=True, help_text='how long does it take to open a task (measurement in hours)', null=True),
        ),
        migrations.AlterField(
            model_name='datetimesort',
            name='how_much',
            field=models.FloatField(blank=True, help_text='how long to open the task (measurement in hours)', null=True),
        ),
    ]
