# Generated by Django 3.2.8 on 2022-12-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20221207_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='avatar',
            field=models.TextField(blank=True, help_text='Text or url to the SVG'),
        ),
    ]
