# Generated by Django 3.2.8 on 2023-01-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_errorgroup_erroritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('expected_task', models.OneToOneField(help_text='task, with the answers you expect to answer', on_delete=django.db.models.deletion.CASCADE, related_name='expected_task', to='api.task')),
                ('sent_task', models.OneToOneField(help_text='task to be sent', on_delete=django.db.models.deletion.CASCADE, related_name='sent_task', to='api.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
