# Generated by Django 3.2.8 on 2023-01-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_testwebhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='which_responses',
            field=models.CharField(choices=[('in', 'In responses'), ('cu', 'Current task responses')], default='in', help_text='Where to copy fields from', max_length=2),
        ),
    ]
