# Generated by Django 3.2.8 on 2023-03-06 09:19

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_userdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonotification',
            name='recipient_stage',
            field=models.ForeignKey(blank=True, help_text='Stage to get recipient user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_notification_recipient_stages', to='api.taskstage'),
        ),
        migrations.AlterField(
            model_name='autonotification',
            name='trigger_stage',
            field=models.ForeignKey(blank=True, help_text='Stage that will be trigger notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_notification_trigger_stages', to='api.taskstage'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_period',
            field=models.DateTimeField(blank=True, help_text='The task will no longer be available to users in (measurement in hours)', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_period',
            field=models.DateTimeField(blank=True, help_text='The task should become available to users in (measurement in hours)', null=True),
        ),
        migrations.CreateModel(
            name='CampaignLinker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('name', models.CharField(help_text='Instance name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Instance description')),
                ('out_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_campaign_linkers_set', to='api.taskstage')),
                ('stage_with_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taskstage')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaign')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, api.models.CampaignInterface),
        ),
        migrations.CreateModel(
            name='ApproveLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaign')),
                ('linker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaignlinker')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.autonotification')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rank')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, api.models.CampaignInterface),
        ),
    ]
