# Generated by Django 3.2.8 on 2023-03-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20230306_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimesort',
            name='after_how_much',
            field=models.FloatField(blank=True, help_text='The task will no longer be available to users in (measurement in hours)', null=True),
        ),
        migrations.AlterField(
            model_name='datetimesort',
            name='how_much',
            field=models.FloatField(blank=True, help_text='The task should become available to users in (measurement in hours)', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_period',
            field=models.DateTimeField(blank=True, help_text='the time until which this task is available', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_period',
            field=models.DateTimeField(blank=True, help_text='the time from which this task is available', null=True),
        ),
    ]
