# Generated by Django 3.2.8 on 2023-03-27 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20230310_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvelink',
            name='approved',
            field=models.BooleanField(default=False, help_text='Status about approved link. False - rank would not be assigned.'),
        ),
        migrations.AddField(
            model_name='approvelink',
            name='task_stage',
            field=models.ForeignKey(blank=True, help_text='Task will created on this stage and assign to the income user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.taskstage'),
        ),
        migrations.AlterField(
            model_name='approvelink',
            name='campaign',
            field=models.ForeignKey(help_text='Campaign that own the campaign linker.', on_delete=django.db.models.deletion.CASCADE, to='api.campaign'),
        ),
        migrations.AlterField(
            model_name='approvelink',
            name='linker',
            field=models.ForeignKey(help_text='Fk linker.', on_delete=django.db.models.deletion.CASCADE, to='api.campaignlinker'),
        ),
        migrations.AlterField(
            model_name='approvelink',
            name='notification',
            field=models.ForeignKey(blank=True, help_text='Auto Notification will create notification to the user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.autonotification'),
        ),
        migrations.AlterField(
            model_name='approvelink',
            name='rank',
            field=models.ForeignKey(blank=True, help_text='Rank that will be assigned to user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rank'),
        ),
        migrations.AlterField(
            model_name='campaignlinker',
            name='out_stage',
            field=models.ForeignKey(blank=True, help_text='Stage that triggers assign new rank to user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_campaign_linkers_set', to='api.taskstage'),
        ),
        migrations.AlterField(
            model_name='campaignlinker',
            name='stage_with_user',
            field=models.ForeignKey(help_text='Stage with user to assignee new rank.', on_delete=django.db.models.deletion.CASCADE, to='api.taskstage'),
        ),
        migrations.AlterField(
            model_name='campaignlinker',
            name='target',
            field=models.ForeignKey(help_text='Target campaign that will see campaign link.', on_delete=django.db.models.deletion.CASCADE, to='api.campaign'),
        ),
    ]
