# Generated by Django 3.2.8 on 2023-03-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_quiz_show_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='descriptor',
            field=models.CharField(blank=True, help_text='Fast description to the campaign to attract new users.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='logo',
            field=models.TextField(blank=True, help_text='Text or url to the SVG'),
        ),
    ]
