# Generated by Django 3.2.8 on 2023-04-18 08:44

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_auto_20230329_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Country name', max_length=526, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ISO language name.', max_length=128)),
                ('code', models.CharField(help_text='Two letters code of language.', max_length=2, validators=[api.models.validate_language_code])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title of category.', max_length=128)),
                ('parents', models.ManyToManyField(blank=True, default=None, help_text='Category that hierarchically upper then this category.', related_name='out_categories', to='api.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, help_text='Categories of the campaign.', to='api.Category'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Language of the campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.language'),
        ),
    ]
