# Generated by Django 3.2.8 on 2023-04-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20230418_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='countries',
            field=models.ManyToManyField(blank=True, default=None, help_text='Countries where campaign works.', to='api.Country'),
        ),
    ]
