# Generated by Django 3.2.8 on 2023-04-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_campaign_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rank',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Priority of the rank in the system.'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='stage_type',
            field=models.CharField(blank=True, choices=[('PR', 'Proactive'), ('RE', 'Reactive')], default=None, help_text='Stage type.', max_length=2, null=True),
        ),
    ]
