# Generated by Django 3.2.8 on 2023-04-25 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20230424_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranklimit',
            name='rank',
            field=models.ForeignKey(help_text='Rank id', on_delete=django.db.models.deletion.CASCADE, related_name='ranklimits', to='api.rank'),
        ),
    ]
