# Generated by Django 3.2.8 on 2023-04-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_alter_ranklimit_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='provide_answers',
            field=models.BooleanField(default=False, help_text='If set as true then with questions title users will see correct answers.'),
        ),
    ]
