# Generated by Django 3.2.8 on 2023-05-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_quiz_provide_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='is_proactive',
            field=models.BooleanField(default=False, help_text='True - stage is proactive, otherwise - active.'),
        ),
    ]
