# Generated by Django 3.2.8 on 2023-05-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_taskstage_is_proactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schema',
            field=models.JSONField(blank=True, default=None, help_text='JSON schema for responses that will supersede schema from Stage.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ui_schema',
            field=models.JSONField(blank=True, default=None, help_text='JSON ui schema for responses that will supersede ui schema from Stage.', null=True),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='schema_source',
            field=models.CharField(choices=[('ST', 'Stage'), ('TA', 'Task')], default='ST', help_text='Flag indicating from where Task should get its schema.', max_length=2),
        ),
        migrations.AddField(
            model_name='webhook',
            name='data',
            field=models.JSONField(blank=True, default=None, help_text='Data that will be sent to webhook if such option is chosen.', null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='target',
            field=models.CharField(choices=[('RE', 'Current task responses'), ('SC', 'Current task schema')], default='RE', help_text='Where response from webhook will be saved.', max_length=2),
        ),
        migrations.AddField(
            model_name='webhook',
            name='ui_schema_field',
            field=models.TextField(blank=True, help_text='JSON response field name to get UI JSON schema from when target is Schema. Ignored when target is not Schema or webhook_address is empty.', null=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='response_field',
            field=models.TextField(blank=True, help_text='JSON response field name to extract data from. If target isSchema, this field is used to access JSON schema. Field is ignored if webhook_address field is empty.', null=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='which_responses',
            field=models.CharField(choices=[('in', 'In responses'), ('cu', 'Current task responses'), ('mf', 'Data field from this modifier')], default='in', help_text='Where to copy fields from', max_length=2),
        ),
    ]
