# Generated by Django 3.2.8 on 2023-05-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20230511_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstage',
            name='is_proactive',
        ),
        migrations.AlterField(
            model_name='taskstage',
            name='stage_type',
            field=models.CharField(blank=True, choices=[('PR', 'Proactive'), ('AC', 'Active')], default=None, help_text='Stage type.', max_length=2, null=True),
        ),
    ]
