# Generated by Django 3.2.8 on 2023-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_auto_20230516_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstage',
            name='stage_type',
            field=models.CharField(blank=True, choices=[('PR', 'Proactive'), ('AC', 'Active')], default='AC', help_text='Stage type.', max_length=2, null=True),
        ),
    ]
