# Generated by Django 3.2.8 on 2023-05-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_alter_taskstage_stage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='target',
        ),
        migrations.AddField(
            model_name='webhook',
            name='internal_meta_field',
            field=models.TextField(blank=True, help_text='JSON response field name to extract data from. If target isSchema, this field is used to access JSON schema. Field is ignored if webhook_address field is empty.', null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='schema_field',
            field=models.TextField(blank=True, help_text='JSON response field name to extract data from. If target isSchema, this field is used to access JSON schema. Field is ignored if webhook_address field is empty.', null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='target_internal_metadata',
            field=models.BooleanField(default=False, help_text="Indicates that response from webhook should be copied into Task's internal metadata"),
        ),
        migrations.AddField(
            model_name='webhook',
            name='target_responses',
            field=models.BooleanField(default=True, help_text="Indicates that response from webhook should be copied into Task's responses"),
        ),
        migrations.AddField(
            model_name='webhook',
            name='target_schema',
            field=models.BooleanField(default=False, help_text="Indicates that response from webhook should be copied into Task's JSON schema"),
        ),
        migrations.AddField(
            model_name='webhook',
            name='target_ui_schema',
            field=models.BooleanField(default=False, help_text="Indicates that response from webhook should be copied into Task's UI schema"),
        ),
    ]
