# Generated by Django 3.2.8 on 2023-05-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20230530_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
