# Generated by Django 3.2.8 on 2023-06-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_auto_20230619_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='request_method',
            field=models.CharField(choices=[('post', 'POST'), ('patch', 'PATCH'), ('put', 'PUT')], default='post', help_text='HTTP method used to make the webhook request.', max_length=6),
        ),
    ]
