# Generated by Django 3.2.8 on 2023-06-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_webhook_request_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='language',
        ),
        migrations.AddField(
            model_name='campaign',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Language of the campaign.', null=True, related_name='campaigns', to='api.Language'),
        ),
    ]
