# Generated by Django 3.2.8 on 2023-07-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20230629_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonotification',
            name='with_response',
            field=models.BooleanField(default=False, help_text='If set as true, so notification text will be sent with Response on task completion.'),
        ),
    ]
