# Generated by Django 3.2.8 on 2023-07-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_autonotification_with_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sms_complete_task_allow',
            field=models.BooleanField(default=False, help_text='If the campaign allows users to send tasks via sms.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sms_phone',
            field=models.CharField(blank=True, help_text='Phone of the campaign to send sms.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ranklimit',
            name='sms_relay_allow',
            field=models.BooleanField(default=False, help_text='Allow user to send task using sms.'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='sms_complete_task_allow',
            field=models.BooleanField(default=False, help_text='If the Task Stage accept tasks via sms.', null=True),
        ),
    ]
