# Generated by Django 3.2.8 on 2023-08-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20230710_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='order_in_individuals',
            field=models.CharField(choices=[('CH', 'Chronologically'), ('GR', 'By Graph order'), ('OR', 'By manually order')], default='CH', help_text='What ordering will be used on tasks return in chain individuals.', max_length=2),
        ),
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the stage in chain.'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='skip_empty_individual_tasks',
            field=models.BooleanField(default=False, help_text="If in individuals chains this stage don't have any tasks - it wouldn't be returned in chain individuals."),
        ),
    ]
