# Generated by Django 3.2.8 on 2023-08-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20230803_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='visible',
            field=models.BooleanField(default=False, help_text='If true - campaigns is visible in the all endpoints. Otherwise it invisible but users can join it.'),
        ),
    ]
