# Generated by Django 3.2.8 on 2023-08-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_campaign_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='available_from',
            field=models.DateTimeField(help_text='Available from.', null=True),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='available_to',
            field=models.DateTimeField(help_text='Available to.', null=True),
        ),
    ]
