# Generated by Django 3.2.8 on 2023-08-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_auto_20230808_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='complete_individual_chain',
            field=models.BooleanField(default=False, help_text='If true and user have tasks on this chain - so chain will be considered as completed.'),
        ),
    ]
