# Generated by Django 3.2.8 on 2023-08-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_taskstage_complete_individual_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstage',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Available from.', null=True),
        ),
        migrations.AlterField(
            model_name='taskstage',
            name='available_to',
            field=models.DateTimeField(blank=True, help_text='Available to.', null=True),
        ),
    ]
