# Generated by Django 3.2.8 on 2023-08-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_auto_20230808_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='taskstage',
            name='stage_type',
            field=models.CharField(blank=True, choices=[('PR', 'Proactive'), ('AC', 'Reactive'), ('PB', 'Proactive buttons')], default='AC', help_text='Stage type.', max_length=2, null=True),
        ),
    ]
