# Generated by Django 3.2.8 on 2023-10-23 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_taskstage_filter_fields_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountTasksModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('field_to_write_count_to', models.TextField(default='task_count', help_text='JSON field in the Task to write count to')),
                ('stage_to_count_tasks_from', models.ForeignKey(help_text='TaskStage whose tasks will be counted', on_delete=django.db.models.deletion.CASCADE, related_name='task_counter', to='api.taskstage')),
                ('task_stage', models.ForeignKey(help_text='Parent TaskStage', on_delete=django.db.models.deletion.CASCADE, related_name='count_tasks_modifier', to='api.taskstage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
