# Generated by Django 3.2.8 on 2023-12-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_taskstage_filter_fields_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='send_answers_with_questions',
            field=models.BooleanField(default=False, help_text='If true answers will be sent alongside questions, useful for exercises.'),
        ),
    ]
