# Generated by Django 3.2.8 on 2023-10-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_counttasksmodifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='counttasksmodifier',
            name='count_unique_users',
            field=models.BooleanField(default=False, help_text='Remove tasks with duplicate user id from count'),
        ),
        migrations.AddField(
            model_name='counttasksmodifier',
            name='field_to_write_count_complete',
            field=models.TextField(default='task_count_complete', help_text='JSON field in the Task to write count complete tasks'),
        ),
    ]
