# Generated by Django 3.2.8 on 2023-12-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_customuser_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='fast_track_rank',
            field=models.ForeignKey(blank=True, help_text='Rank that will be given when using fast_track', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fast_track_rank', to='api.rank'),
        ),
    ]
