# Generated by Django 3.2.8 on 2023-11-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20231026_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='send_answers_with_questions',
            field=models.BooleanField(default=False, help_text='If true answers will be sent alongside questions, useful for exercises.'),
        ),
        migrations.DeleteModel(
            name='CountTasksModifier',
        ),
    ]
