# Generated by Django 3.2.8 on 2024-07-10 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_taskstage_fast_track_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('name', models.CharField(help_text='Instance name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Instance description')),
                ('order', models.IntegerField(help_text='Order inside track')),
                ('not_yet_open_message', models.TextField(blank=True, help_text="Message for users when volume isn't yet opened", null=True)),
                ('already_closed_message', models.TextField(blank=True, help_text='Message for users when volume is already closed', null=True)),
                ('show_tags', models.BooleanField(default=False, help_text='Flag to determine if tags should be shown for the volume', null=True)),
                ('show_tags_filter', models.BooleanField(default=False, help_text='Flag to determine if tags should be shown for the volume (filter)', null=True)),
                ('my_tasks_text', models.TextField(blank=True, help_text="Text to display for 'My Tasks' section related to the volume", null=True)),
                ('active_tasks_text', models.TextField(blank=True, help_text="Text to display for 'Active Tasks' section related to the volume", null=True)),
                ('returned_tasks_text', models.TextField(blank=True, help_text="Text to display for 'Returned Tasks' section related to the volume", null=True)),
                ('completed_tasks_text', models.TextField(blank=True, help_text="Text to display for 'Completed Tasks' section related to the volume", null=True)),
                ('closing_ranks', models.ManyToManyField(help_text='Ranks needed to close this volume', related_name='closing_ranks', to='api.Rank')),
                ('opening_ranks', models.ManyToManyField(help_text='Ranks needed to open this volume', related_name='opening_ranks', to='api.Rank')),
                ('track_fk', models.ForeignKey(help_text='Track this volume belongs to.', on_delete=django.db.models.deletion.CASCADE, to='api.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('name', models.CharField(help_text='Instance name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Instance description')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stage')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.volume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='volumes',
            field=models.ManyToManyField(blank=True, help_text='List of available volumes', related_name='stage_volumes', through='api.StageVolume', to='api.Volume'),
        ),
    ]
