# Generated by Django 3.2.8 on 2024-07-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_auto_20240710_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionalstage',
            name='prevent_duplicate',
            field=models.BooleanField(default=False, help_text='If true prevents duplicate task creation'),
        ),
    ]
