# Generated by Django 3.2.8 on 2024-07-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_conditionalstage_prevent_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='external_renderer_url',
            field=models.URLField(blank=True, help_text='External renderer url', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='take_task_button_text',
            field=models.CharField(blank=True, help_text='Text that will be shown on the take task button', max_length=128, null=True),
        ),
    ]
