# Generated by Django 3.2.8 on 2024-11-05 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20241105_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='registration_stage',
            field=models.ForeignKey(blank=True, help_text='Registration stage', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.taskstage'),
        ),
    ]
