# Generated by Django 3.2.8 on 2024-11-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_track_registration_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='closed',
            field=models.BooleanField(default=False, help_text='Flag to determine if Volume closed', null=True),
        ),
    ]
