# Generated by Django 3.2.8 on 2024-12-09 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_volume_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='course_completetion_rank',
            field=models.ForeignKey(blank=True, help_text='Check if user has the rank, to determine course completion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rank'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date when the course will start', null=True),
        ),
    ]
