# Generated by Django 3.2.8 on 2025-01-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_auto_20241209_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='is_text_book',
            field=models.BooleanField(default=False, help_text='If true, this chain is a text book, which means its stages containing rich text will accessible at once to any logged in user but without any tasks, tests, or progress tracking.'),
        ),
        migrations.AlterField(
            model_name='chain',
            name='is_individual',
            field=models.BooleanField(default=False, help_text='If true, this chain is an individual chain.'),
        ),
    ]
