# Generated by Django 3.2.8 on 2025-02-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_auto_20250130_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='closing_ranks',
            field=models.ManyToManyField(help_text='Ranks needed to close this volume', related_name='closed_volumes', to='api.Rank'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='opening_ranks',
            field=models.ManyToManyField(help_text='Ranks needed to open this volume', related_name='opened_volumes', to='api.Rank'),
        ),
    ]
