# Generated by Django 3.2.8 on 2025-02-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_auto_20250205_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='new_task_view_mode',
        ),
        migrations.AddField(
            model_name='chain',
            name='new_task_view_mode',
            field=models.BooleanField(default=False, help_text='Use new task view mode'),
        ),
    ]
