# Generated by Django 3.2.8 on 2024-11-25 09:01

from django.db import migrations, models
import django.db.models.deletion
import okutool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0125_volume_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('title', models.TextField(blank=True, null=True)),
                ('json_schema', models.JSONField(blank=True, null=True)),
                ('ui_schema', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_limit', models.IntegerField(default=0, help_text='Limit the number of questions shown')),
                ('passing_score', models.IntegerField(default=0)),
                ('order_by', models.CharField(choices=[('RND', 'Random'), ('IND', 'Index')], default='RND', max_length=3)),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='api.taskstage')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AU', 'Audio'), ('IM', 'Image'), ('VI', 'Video'), ('OT', 'Other file types')], max_length=2)),
                ('file', models.FileField(upload_to=okutool.models.attachment_upload_path)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='okutool.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='okutool.test'),
        ),
    ]
